#!/usr/bin/env bash
# One-click Ubuntu setup for YHorizon-JM.
# Installs missing packages via apt when needed, then creates the Python SDK venv.
#
#   ./tools/setup-env.sh
#   ./tools/setup-env.sh --skip-host
#   ./tools/setup-env.sh --build

set -euo pipefail

SKIP_HOST=0
SKIP_FLASH=0
DO_BUILD=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-host) SKIP_HOST=1; shift ;;
        --skip-flash) SKIP_FLASH=1; shift ;;
        --build) DO_BUILD=1; shift ;;
        -h|--help)
            sed -n '2,8p' "$0"
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=yhjm-env.sh
. "${SCRIPT_DIR}/yhjm-env.sh"
yhjm_import_env

yhjm_step() {
    printf '\n==> %s\n' "$1"
}

yhjm_apt_install() {
    local pkgs=("$@")
    if ((${#pkgs[@]} == 0)); then
        return 0
    fi
    if ! command -v apt-get >/dev/null 2>&1; then
        echo "apt-get not found. Install: ${pkgs[*]}" >&2
        exit 1
    fi
    yhjm_step "apt install ${pkgs[*]}"
    if [[ "$(id -u)" -eq 0 ]]; then
        DEBIAN_FRONTEND=noninteractive apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y "${pkgs[@]}"
    elif command -v sudo >/dev/null 2>&1; then
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "${pkgs[@]}"
    else
        echo "need root or sudo to install: ${pkgs[*]}" >&2
        exit 1
    fi
}

echo "YHorizon-JM setup  ${YHJM_ROOT}"

need_pkgs=()
command -v cmake >/dev/null 2>&1 || need_pkgs+=(cmake)
command -v ninja >/dev/null 2>&1 || need_pkgs+=(ninja-build)
command -v arm-none-eabi-gcc >/dev/null 2>&1 || need_pkgs+=(gcc-arm-none-eabi)
if [[ "${SKIP_FLASH}" -eq 0 ]]; then
    command -v openocd >/dev/null 2>&1 || need_pkgs+=(openocd)
fi
if [[ "${SKIP_HOST}" -eq 0 ]]; then
    if ! command -v python3 >/dev/null 2>&1; then
        need_pkgs+=(python3 python3-venv python3-pip)
    else
        python3 -c "import venv" >/dev/null 2>&1 || need_pkgs+=(python3-venv)
        python3 -c "import pip" >/dev/null 2>&1 || need_pkgs+=(python3-pip)
    fi
    command -v candump >/dev/null 2>&1 || need_pkgs+=(can-utils)
fi

yhjm_apt_install "${need_pkgs[@]}"

cmake_exe="$(yhjm_find_cmake)" || { echo "cmake not found" >&2; exit 1; }
ninja_exe="$(yhjm_find_ninja)" || { echo "ninja not found" >&2; exit 1; }
gcc_exe="$(yhjm_find_arm_gcc)" || { echo "arm-none-eabi-gcc not found" >&2; exit 1; }

openocd_exe=""
openocd_scripts=""
openocd_gd32=0
if [[ "${SKIP_FLASH}" -eq 0 ]]; then
    if yhjm_find_openocd; then
        openocd_exe="${YHJM_OPENOCD_EXE}"
        openocd_scripts="${YHJM_OPENOCD_SCRIPTS}"
        openocd_gd32="${YHJM_OPENOCD_HAS_GD32}"
    else
        echo "openocd not found (use --skip-flash to continue)" >&2
        exit 1
    fi
fi

if [[ "${SKIP_HOST}" -eq 0 ]]; then
    yhjm_step "Python SDK (servo_gui)"
    py="$(yhjm_find_python)" || {
        echo "Python 3.10+ not found. Install python3 python3-venv python3-pip, or skip with --skip-host." >&2
        exit 1
    }
    venv="${YHJM_SDK_PYTHON}/.venv"
    venv_py="${venv}/bin/python"
    if [[ ! -x "${venv_py}" ]]; then
        echo "venv: ${venv}"
        "${py}" -m venv "${venv}"
    fi
    echo "pip: ${YHJM_SDK_PYTHON}/requirements.txt"
    "${venv_py}" -m pip install --upgrade pip
    "${venv_py}" -m pip install -r "${YHJM_SDK_PYTHON}/requirements.txt"
    echo "sdk python: ${venv_py}"
fi

cmake_dir="$(dirname "${cmake_exe}")"
ninja_dir="$(dirname "${ninja_exe}")"
gcc_dir="$(dirname "${gcc_exe}")"
path_parts=("${gcc_dir}" "${cmake_dir}" "${ninja_dir}")
if [[ -n "${openocd_exe}" ]]; then
    path_parts+=("$(dirname "${openocd_exe}")")
fi
path_join="$(IFS=:; echo "${path_parts[*]}")"

cat > "${SCRIPT_DIR}/env.sh" <<EOF
# Generated by tools/setup-env.sh. Do not edit.
export ARM_NONE_EABI_TOOLCHAIN_PATH='${gcc_dir}'
export YHJM_OPENOCD_EXE='${openocd_exe}'
export YHJM_OPENOCD_SCRIPTS='${openocd_scripts}'
export YHJM_OPENOCD_HAS_GD32='${openocd_gd32}'
export PATH='${path_join}:'"\${PATH}"
EOF
echo "wrote: ${SCRIPT_DIR}/env.sh"
# shellcheck source=/dev/null
. "${SCRIPT_DIR}/env.sh"

yhjm_step "Summary"
echo "cmake              ${cmake_exe}"
echo "ninja              ${ninja_exe}"
echo "arm-none-eabi-gcc  ${gcc_exe}"
if [[ -n "${openocd_exe}" ]]; then
    echo "openocd            ${openocd_exe}"
    if [[ "${openocd_gd32}" -eq 1 ]]; then
        echo "flash driver       gd32f30x"
    else
        echo "flash driver       stm32f1x fallback (256 KB, no mass_erase)"
        echo "Ubuntu OpenOCD usually has no gd32f30x driver; that is expected."
    fi
else
    echo "openocd            (skipped)"
fi
echo
echo "Next:"
echo "  ./tools/build.sh"
echo "  ./tools/flash.sh          # CMSIS-DAP + SWD"
echo "  ./tools/run-gui.sh"
echo "SocketCAN example: sudo ip link set can0 up type can bitrate 1000000"
echo "If the debugger is not visible, add your user to plugdev/dialout and replug:"
echo "  sudo usermod -aG plugdev,dialout \"\$USER\""

if [[ "${DO_BUILD}" -eq 1 ]]; then
    yhjm_step "Build"
    "${SCRIPT_DIR}/build.sh"
fi
